### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by mikolas2788** [evanhundred/yup#2]
# MVP List
- [x] Should have 7 MVPs.
  - [x] 3 of those are User Auth, Render, and Production README.
  - [x] The other 4 are from the [Approved Apps List](https://github.com/appacademy/cohort-resources/blob/master/full_stack_projects/aa_approved_full_stack_projects.md) or your PM will have clarified them with you
- [x] Contains a description sentence of the app
- [ ] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [ ] Correctly formatted
  - [ ] MVPs are listed in an ordered list
  - [x] Each MVP is broken down into bullet points

**Comment by PedroKim** [comment]
- See if you can add another bullet point describing functionality for Search and Reviews & Rating MVP. 
- Have your main 7 MVPs numbered.
- Include due dates, next to duration of each task. (e.g. 1. App is hosted (12/05/22, 1 day)

**Comment by evanhundred** [comment]
1. bullet points/functionality added for Search, Review + Rating
2. MVPs numbered in list
3. Due dates added to time estimate 

See if you can add another bullet point describing functionality for Search and Reviews & Rating MVP.
Have your main 7 MVPs numbered.
Include due dates, next to duration of each task. (e.g. 1. App is hosted (12/05/22, 1 day)
