### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by mikolas2788** [evanhundred/yup#3]
# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
  - [x] primary key
  - [x] not null
  - [x] unique
  - [x] indexed
  - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
  - [x] schema is written in a table format
  - [x] the table's name are lowercased, snake_cased and `back_ticked`
  - [x] the table header column names are bolded
  - [x] columns names are lowercased and snaked_cased and `back_ticked`

**Comment by PedroKim** [comment]
- [ ] missing bullet point for `owner_id` referencing `users` under businesses.
- [ ] include index on `owner_id` bullet point under businesses.
- [ ] you won't need image_url columns as it will be done by Active Storage (which is hooking up AWS).
- [ ] `review_ids` won't be necessary as `reviews` association will provide a method for you to just generate array of ids.

**Comment by evanhundred** [comment]
1. added bullet point for `owner_id` in `businesses` table
2. added bullet point for index on `owner_id`
3. removed column for `image_url` in `users` and `businesses` tables
4. removed column for `review_ids` in `businesses` table
